src/assets/style.css, src/bumper.js
Always create the bumper click through element
=> fix(FEC-9191): when clickthrough isn't configured, the bumper doesn't paused by clicking

src/assets/style.css
calculate `height` automatically
=> fix(FEC-9193): the bumper isn't extended to all player area

src/assets/style.css, src/bumper.js
set `height:100%` when the player in full screen mode
=> fix(FEC-9211): full screen not applied on the bumper

karma.conf.js, src/bumper.js, test/src/bumper.spec.js
do not trigger `AD_PAUSED` on ad finish
=> fix(FEC-9217): Youbora fired adPause and adStop events when the bumper finished

package.json, src/bumper-ads-controller.js, src/bumper-middleware.js, src/bumper.js, test/src/bumper.spec.js, yarn.lock
* Support bumper preloading
* Implement `LOAD` middleware
Depends on 
https://github.com/kaltura/playkit-js/pull/377
https://github.com/kaltura/playkit-js-ui/pull/397
=> feat(FEC-9159): preload support

src/bumper.js, test/src/bumper.spec.js
change Bumper event sequence to work as IMA
=> feat(FEC-9227): support reInit of MSE

src/bumper-middleware.js, src/bumper.js, test/src/bumper.spec.js
load the post bumper 3 seconds before ended
=> fix(FEC-9265): post bumper pre-loaded too early

src/bumper.js
make sure `complete` promise is set
=> fix(FEC-9276): post-roll is not displayed when configure bumper with empty url

src/bumper.js
=> fix(FEC-9426): when pause bumper on full screen and exit full screen bumper start play

.travis.yml, test/src/bumper.spec.js
update ubuntu version on travis
=> chore: Chrome failed on travis - update travis.yml

test/src/bumper.spec.js
use production bumper and consts
=> chore: fix tests

src/bumper-engine-decorator.js, src/bumper-middleware.js, src/bumper.js, test/src/bumper.spec.js
* Handle play promise rejection 
* Add `BumperType` enum
Solves [FEC-9513](https://kaltura.atlassian.net/browse/FEC-9513)
=> fix(FEC-9513): endless spinner when auto play is failed

src/bumper-engine-decorator.js, src/bumper-middleware.js, src/bumper.js, test/src/bumper.spec.js
=> revert "fix(FEC-9513): endless spinner when auto play is failed (#33)"

.travis.yml
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
=> chore: travis missing key issue with NPM with dpl.2

.flowconfig, flow-typed/modules/kaltura-player-js.js, package.json, src/bumper-engine-decorator.js, src/bumper-middleware.js, src/bumper.js, src/index.js, test/src/bumper.spec.js, test/src/utils/test-utils.js, webpack.config.js, yarn.lock
import the plugin infra and types from kaltura-player
Depends on kaltura/kaltura-player-js#332
=> feat(FEC-10057): move the plugin manager to kaltura player

src/bumper.js, test/src/bumper.spec.js
set the click through url on `updateConfig`
Solves FEC-10673
=> fix(FEC-10673): back-end bumper : no clickthrough works

package.json, src/bumper-ads-controller.js, yarn.lock
remove the empty implementation and check for API in kaltura player.
=> fix(FEC-11062): ad layout doesn't work when IMA DAI configured

README.md
=> chore(FEC-13123): replace travis with github actions 

.flowconfig, .github/workflows/run_canary_full_flow.yaml, .github/workflows/run_prod.yaml, .github/workflows/run_tests.yaml, package.json, src/bumper-engine-decorator.js, src/bumper-middleware.js, src/bumper.js, src/index.js, test/src/bumper.spec.js, webpack.config.js, yarn.lock
=> fix(FEC-13123): replace travis with github actions

src/bumper.js, src/events/events.js, src/events/index.js, src/index.js
Add Events (used by kava analytics)
https://github.com/kaltura/playkit-js-kava/pull/156
=> fix(FEC-13743): [Bumper Plugin]: Add Events (used by kava analytics)
